// tools/Testimonials/settings.js
export const mkTestDesktop = () => ({
  layout: "card-grid",
  columns: 3,
  sectionBg: "#ffffff",
  cardBg: "#ffffff",
  cardBorderColor: "#e5e7eb",
  cardBorderWidth: 1,
  cardRadius: 14,
  cardPadding: 24,
  cardGap: 20,
  showShadow: false,
  shadowX: 0,
  shadowY: 2,
  shadowBlur: 16,
  shadowSpread: 0,
  shadowColor: "rgba(0,0,0,0.08)",
  maxWidth: 1100,
  quoteColor: "#1f2937",
  quoteSize: 15,
  quoteWeight: "400",
  quoteFont: "Inter",
  quoteAlign: "left",
  nameColor: "#111827",
  nameSize: 14,
  nameWeight: "600",
  nameFont: "Inter",
  roleColor: "#6b7280",
  roleSize: 12,
  roleWeight: "400",
  roleFont: "Inter",
  starColor: "#f59e0b",
  starSize: 16,
  showStars: true,
  avatarSize: 48,
  avatarRadius: 50,
  showAvatar: true,
  showCompany: true,
  companyColor: "#9ca3af",
  companySize: 11,
  quoteMarkColor: "#1a1a18",
  quoteMarkSize: 48,
  showQuoteMark: true,
  navStyle: "sides",
  navBtnBg: "#ffffff",
  navBtnColor: "#111827",
  navBtnRadius: 50,
  navBtnSize: 36,
  navBtnIcon: "arrow",
  navBtnCustomPrev: "←",
  navBtnCustomNext: "→",
  showDots: true,
  dotColor: "#1a1a18",
  dotSize: 8,
  autoPlay: false,
  autoPlaySpeed: 3000,
});

export const mkTestTablet = () => ({
  ...mkTestDesktop(),
  columns: 2,
  cardPadding: 18,
  quoteSize: 14,
  maxWidth: 700,
});
export const mkTestMobile = () => ({
  ...mkTestDesktop(),
  columns: 1,
  layout: "carousel",
  cardPadding: 16,
  quoteSize: 13,
  maxWidth: 400,
  navStyle: "bottom",
});

export const DEFAULT_TESTIMONIALS = [
  {
    id: 1,
    name: "Sarah Chen",
    role: "CEO",
    company: "NovaTech",
    quote:
      "This product completely transformed how our team works. The ROI was visible within the first month. Absolutely game-changing.",
    stars: 5,
    initials: "SC",
    avatarBg: "#1a1a18",
    avatarUrl: null,
  },
  {
    id: 2,
    name: "Marcus Reid",
    role: "Product Lead",
    company: "Stride Labs",
    quote:
      "I've tried dozens of tools and nothing comes close. The attention to detail is remarkable and the support team is outstanding.",
    stars: 5,
    initials: "MR",
    avatarBg: "#0ea5e9",
    avatarUrl: null,
  },
  {
    id: 3,
    name: "Priya Kapoor",
    role: "Founder",
    company: "Bloom Agency",
    quote:
      "Switched from a competitor and never looked back. Setup took under an hour and the results speak for themselves.",
    stars: 4,
    initials: "PK",
    avatarBg: "#f59e0b",
    avatarUrl: null,
  },
  {
    id: 4,
    name: "James Okafor",
    role: "Marketing Dir",
    company: "Vanta Co",
    quote:
      "Our conversion rate jumped 40% after implementing this. The team was incredibly helpful throughout the onboarding process.",
    stars: 5,
    initials: "JO",
    avatarBg: "#10b981",
    avatarUrl: null,
  },
  {
    id: 5,
    name: "Lena Fischer",
    role: "CTO",
    company: "Axle Systems",
    quote:
      "Rock-solid reliability and a developer experience that's truly a joy. We've built our entire pipeline around this platform.",
    stars: 5,
    initials: "LF",
    avatarBg: "#ec4899",
    avatarUrl: null,
  },
  {
    id: 6,
    name: "Tom Nguyen",
    role: "Operations",
    company: "Scale HQ",
    quote:
      "The automation features alone saved us 20 hours a week. I recommend it to every founder I meet.",
    stars: 4,
    initials: "TN",
    avatarBg: "#8b5cf6",
    avatarUrl: null,
  },
];
